export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const GET_SEGMENT_SUCCESS = 'GET_SEGMENT_SUCCESS'
export const GET_SEGMENT_LOADING = 'GET_SEGMENT_LOADING'

export const ADD_RECORDING_TO_STORE = 'ADD_RECORDING_TO_STORE'
export const UPLOAD_RECORDING_STARTED = 'UPLOAD_RECORDING_STARTED'
export const UPLOAD_RECORDING_SUCCESS = 'UPLOAD_RECORDING_SUCCESS'

export const TOGGLE_IS_PLAYING = 'TOGGLE_IS_PLAYING'

export const REMOVE_ACTIVE_AUDIO_CONFIG = 'REMOVE_ACTIVE_AUDIO_CONFIG'
export const SET_ACTIVE_AUDIO_CONFIG = 'SET_ACTIVE_AUDIO_CONFIG'
export const START_MOCK_RECORDING = 'START_MOCK_RECORDING'
export const STOP_MOCK_RECORDING = 'STOP_MOCK_RECORDING'

export const SET_AUDIO_ELEMENT = 'SET_AUDIO_ELEMENT'
export const STOP_PLAYING_AUDIO_ELEMENT = 'STOP_PLAYING_AUDIO_ELEMENT'

export const EXPAND_HEADER = 'EXPAND_HEADER'
export const CONTRACT_HEADER = 'CONTRACT_HEADER'

export const ACTIVATE_SETTINGS_SCREEN = 'ACTIVATE_SETTINGS_SCREEN'
export const ACTIVATE_INTERACTIVE_SCREEN = 'ACTIVATE_INTERACTIVE_SCREEN'
export const ACTIVATE_RECENT_RECORDINGS = 'ACTIVATE_RECENT_RECORDINGS'
export const ACTIVATE_ABOUT = 'ACTIVATE_ABOUT'
export const ACTIVATE_LISTEN = 'ACTIVATE_LISTEN'

export const LOAD_USER_SETTINGS_STARTED = 'LOAD_USER_SETTINGS_STARTED'
export const LOAD_USER_SETTINGS_SUCCESS = 'LOAD_USER_SETTINGS_SUCCESS'
export const UPDATE_USER_SETTINGS_STARTED = 'UPDATE_USER_SETTINGS_STARTED'
export const UPDATE_USER_SETTINGS_SUCCESS = 'UPDATE_USER_SETTINGS_SUCCESS'

export const SET_IDENTITY_TYPE = 'SET_IDENTITY_TYPE'
