export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const GET_SEGMENT_SUCCESS = 'GET_SEGMENT_SUCCESS'
export const GET_SEGMENT_LOADING = 'GET_SEGMENT_LOADING'

export const ADD_RECORDING_TO_STORE = 'ADD_RECORDING_TO_STORE'
export const UPLOAD_RECORDING_STARTED = 'UPLOAD_RECORDING_STARTED'
export const UPLOAD_RECORDING_SUCCESS = 'UPLOAD_RECORDING_SUCCESS'

export const TOGGLE_IS_PLAYING = 'TOGGLE_IS_PLAYING'

export const START_RECORDING = 'START_RECORDING'
export const STOP_RECORDING = 'STOP_RECORDING'
export const START_MOCK_RECORDING = 'START_MOCK_RECORDING'
export const STOP_MOCK_RECORDING = 'STOP_MOCK_RECORDING'

export const EXPAND_HEADER = 'EXPAND_HEADER'
export const CONTRACT_HEADER = 'CONTRACT_HEADER'

export const ACTIVATE_SETTINGS_SCREEN = 'ACTIVATE_SETTINGS_SCREEN'
export const ACTIVATE_INTERACTIVE_SCREEN = 'ACTIVATE_INTERACTIVE_SCREEN'
